"""normalize study versions

Revision ID: 0011_study_versions
Revises: 0010_fulltext_screening
Create Date: 2026-09-24 23:21:19.255422
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0011_study_versions'
down_revision: Union[str, Sequence[str], None] = '0010_fulltext_screening'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_studies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_paper_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_paper_id'], ['papers.id'], name=op.f('fk_canonical_studies_canonical_paper_id_papers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_studies')),
    sa.UniqueConstraint('canonical_paper_id', name=op.f('uq_canonical_studies_canonical_paper_id'))
    )
    op.create_table('study_link_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_a_id', sa.Uuid(), nullable=False),
    sa.Column('paper_b_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=False),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.Column('decision_source', sa.String(length=16), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('confirmed', 'unresolved', 'rejected')", name=op.f('ck_study_link_candidates_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_study_link_candidates_confidence_range')),
    sa.CheckConstraint('paper_a_id <> paper_b_id', name=op.f('ck_study_link_candidates_different_papers')),
    sa.ForeignKeyConstraint(['paper_a_id'], ['papers.id'], name=op.f('fk_study_link_candidates_paper_a_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_b_id'], ['papers.id'], name=op.f('fk_study_link_candidates_paper_b_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_link_candidates')),
    sa.UniqueConstraint('paper_a_id', 'paper_b_id', name='uq_study_link_candidate_pair')
    )
    op.create_index('ix_study_link_candidates_status', 'study_link_candidates', ['status'], unique=False)
    op.create_table('study_papers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('publication_role', sa.String(length=16), nullable=False),
    sa.Column('relationship_reason', sa.Text(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("publication_role IN ('preprint', 'conference', 'journal', 'other')", name=op.f('ck_study_papers_publication_role_valid')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_study_papers_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['canonical_studies.id'], name=op.f('fk_study_papers_study_id_canonical_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_papers')),
    sa.UniqueConstraint('paper_id', name=op.f('uq_study_papers_paper_id'))
    )
    op.create_index('ix_study_papers_study_role', 'study_papers', ['study_id', 'publication_role'], unique=False)
    op.create_table('study_run_selections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_paper_version_id', sa.Uuid(), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preferred_paper_version_id'], ['paper_versions.id'], name=op.f('fk_study_run_selections_preferred_paper_version_id_paper_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_study_run_selections_run_id_research_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['canonical_studies.id'], name=op.f('fk_study_run_selections_study_id_canonical_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_run_selections')),
    sa.UniqueConstraint('run_id', 'study_id', name='uq_study_run_selection')
    )
    op.create_table('study_version_comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('version_a_id', sa.Uuid(), nullable=False),
    sa.Column('version_b_id', sa.Uuid(), nullable=False),
    sa.Column('result_relation', sa.String(length=24), nullable=False),
    sa.Column('assessment_source', sa.String(length=16), nullable=False),
    sa.Column('assessment_note', sa.Text(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result_relation IN ('identical_content', 'not_assessed', 'equivalent', 'changed')", name=op.f('ck_study_version_comparisons_result_relation_valid')),
    sa.CheckConstraint('version_a_id <> version_b_id', name=op.f('ck_study_version_comparisons_different_versions')),
    sa.ForeignKeyConstraint(['study_id'], ['canonical_studies.id'], name=op.f('fk_study_version_comparisons_study_id_canonical_studies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_a_id'], ['paper_versions.id'], name=op.f('fk_study_version_comparisons_version_a_id_paper_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_b_id'], ['paper_versions.id'], name=op.f('fk_study_version_comparisons_version_b_id_paper_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_version_comparisons')),
    sa.UniqueConstraint('study_id', 'version_a_id', 'version_b_id', name='uq_study_version_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_version_comparisons')
    op.drop_table('study_run_selections')
    op.drop_index('ix_study_papers_study_role', table_name='study_papers')
    op.drop_table('study_papers')
    op.drop_index('ix_study_link_candidates_status', table_name='study_link_candidates')
    op.drop_table('study_link_candidates')
    op.drop_table('canonical_studies')
    # ### end Alembic commands ###
