"""add evidence ledger

Revision ID: 0012_evidence_ledger
Revises: 0011_study_versions
Create Date: 2026-09-25 11:33:18.655361
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0012_evidence_ledger'
down_revision: Union[str, Sequence[str], None] = '0011_study_versions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_generations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name=op.f('ck_claim_generations_status_valid')),
    sa.ForeignKeyConstraint(['plan_id'], ['research_plans.id'], name=op.f('fk_claim_generations_plan_id_research_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_claim_generations_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_generations')),
    sa.UniqueConstraint('run_id', 'input_hash', name='uq_claim_generation_input')
    )
    op.create_index('ix_claim_generations_run_created', 'claim_generations', ['run_id', 'created_at'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('sub_question_index', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('basis_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('basis_quote', sa.Text(), nullable=False),
    sa.Column('basis_chunk_char_start', sa.Integer(), nullable=False),
    sa.Column('basis_chunk_char_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('basis_chunk_char_end > basis_chunk_char_start', name=op.f('ck_claims_basis_range_valid')),
    sa.CheckConstraint('sub_question_index >= 0', name=op.f('ck_claims_subquestion_nonnegative')),
    sa.ForeignKeyConstraint(['basis_chunk_id'], ['chunks.id'], name=op.f('fk_claims_basis_chunk_id_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generation_id'], ['claim_generations.id'], name=op.f('fk_claims_generation_id_claim_generations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('generation_id', 'sub_question_index', name='uq_claim_generation_subquestion')
    )
    op.create_table('evidence_extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('paper_version_id', sa.Uuid(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('retrieval_model_revision', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=True),
    sa.Column('no_evidence_reason', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disposition IS NULL OR disposition IN ('evidence', 'no_evidence')", name=op.f('ck_evidence_extractions_disposition_valid')),
    sa.CheckConstraint("status IN ('success', 'failed')", name=op.f('ck_evidence_extractions_status_valid')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_extractions_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.id'], name=op.f('fk_evidence_extractions_paper_version_id_paper_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_id'], ['canonical_studies.id'], name=op.f('fk_evidence_extractions_study_id_canonical_studies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_extractions')),
    sa.UniqueConstraint('claim_id', 'study_id', 'paper_version_id', 'input_hash', name='uq_evidence_extraction_input')
    )
    op.create_index('ix_evidence_extractions_claim_study', 'evidence_extractions', ['claim_id', 'study_id'], unique=False)
    op.create_table('evidence_spans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('paper_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('study_context', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('chunk_char_start', sa.Integer(), nullable=False),
    sa.Column('chunk_char_end', sa.Integer(), nullable=False),
    sa.Column('page_char_start', sa.Integer(), nullable=False),
    sa.Column('page_char_end', sa.Integer(), nullable=False),
    sa.Column('locator', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stance IN ('supports', 'contradicts', 'qualifies', 'unrelated')", name=op.f('ck_evidence_spans_stance_valid')),
    sa.CheckConstraint('chunk_char_end > chunk_char_start', name=op.f('ck_evidence_spans_chunk_range_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_evidence_spans_confidence_range')),
    sa.CheckConstraint('page_char_end > page_char_start', name=op.f('ck_evidence_spans_page_range_valid')),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_evidence_spans_page_positive')),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_evidence_spans_chunk_id_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extraction_id'], ['evidence_extractions.id'], name=op.f('fk_evidence_spans_extraction_id_evidence_extractions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.id'], name=op.f('fk_evidence_spans_paper_version_id_paper_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_id'], ['canonical_studies.id'], name=op.f('fk_evidence_spans_study_id_canonical_studies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_spans')),
    sa.UniqueConstraint('extraction_id', 'chunk_id', 'chunk_char_start', 'chunk_char_end', name='uq_evidence_span_exact_quote')
    )
    op.create_index('ix_evidence_spans_study_stance', 'evidence_spans', ['study_id', 'stance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_spans_study_stance', table_name='evidence_spans')
    op.drop_table('evidence_spans')
    op.drop_index('ix_evidence_extractions_claim_study', table_name='evidence_extractions')
    op.drop_table('evidence_extractions')
    op.drop_table('claims')
    op.drop_index('ix_claim_generations_run_created', table_name='claim_generations')
    op.drop_table('claim_generations')
    # ### end Alembic commands ###
