"""scope claim assertions

Revision ID: 0013_claim_scopes
Revises: 0012_evidence_ledger
Create Date: 2026-09-25 12:04:38.626937
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0013_claim_scopes'
down_revision: Union[str, Sequence[str], None] = '0012_evidence_ledger'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_generations', sa.Column('no_claim_reason', sa.Text(), nullable=True))
    op.add_column('claims', sa.Column('scope_kind', sa.String(length=20), server_default='cross_study', nullable=False))
    op.add_column('claims', sa.Column('basis_study_id', sa.Uuid(), nullable=True))
    op.create_check_constraint('ck_claims_scope_kind_valid', 'claims',
                               "scope_kind IN ('study_specific', 'cross_study')")
    op.create_foreign_key(op.f('fk_claims_basis_study_id_canonical_studies'), 'claims', 'canonical_studies', ['basis_study_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_claims_basis_study_id_canonical_studies'), 'claims', type_='foreignkey')
    op.drop_constraint('ck_claims_scope_kind_valid', 'claims', type_='check')
    op.drop_column('claims', 'basis_study_id')
    op.drop_column('claims', 'scope_kind')
    op.drop_column('claim_generations', 'no_claim_reason')
    # ### end Alembic commands ###
